// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PowerUp.Data;

#nullable disable

namespace PowerUp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241123004910_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PowerUp.Models.AlternativaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("ECorreta")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("e_correta");

                    b.Property<int>("PerguntaId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("PerguntaId");

                    b.ToTable("ALTERNATIVA");
                });

            modelBuilder.Entity("PowerUp.Models.ArtigoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ModuloEducativoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Subtitulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int>("ThumbLinkId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.HasKey("Id");

                    b.HasIndex("ModuloEducativoId");

                    b.HasIndex("ThumbLinkId");

                    b.ToTable("artigo");
                });

            modelBuilder.Entity("PowerUp.Models.DesafioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int>("QuizId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ThumbLinkId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("ThumbLinkId");

                    b.ToTable("desafio");
                });

            modelBuilder.Entity("PowerUp.Models.EmblemaConfigModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("EmblemaTipoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("QuizId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("EmblemaTipoId");

                    b.HasIndex("QuizId");

                    b.ToTable("emblema_config");
                });

            modelBuilder.Entity("PowerUp.Models.EmblemaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmblemaConfigId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("EmblemaConfigId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("emblema");
                });

            modelBuilder.Entity("PowerUp.Models.EmblemaTipoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ImageLinkId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.HasKey("Id");

                    b.HasIndex("ImageLinkId");

                    b.ToTable("emblema_tipo");
                });

            modelBuilder.Entity("PowerUp.Models.LinkModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.HasKey("Id");

                    b.ToTable("link");
                });

            modelBuilder.Entity("PowerUp.Models.MissaoArtigoModel", b =>
                {
                    b.Property<int>("MissaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ArtigoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Artigo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Missao")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("MissaoId", "ArtigoId");

                    b.ToTable("missao_artigo");
                });

            modelBuilder.Entity("PowerUp.Models.MissaoConfigModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<int>("FrequenciaDias")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("frequencia_dias");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("Pontos")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("missao_config");
                });

            modelBuilder.Entity("PowerUp.Models.MissaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MissaoConfigId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("RecompensaPontos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("recompensa_pontos");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("MissaoConfigId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("missao");
                });

            modelBuilder.Entity("PowerUp.Models.MissaoModuloModel", b =>
                {
                    b.Property<int>("MissaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ModuloEducativoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Missao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ModuloEducativo")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("MissaoId", "ModuloEducativoId");

                    b.ToTable("missao_modulo");
                });

            modelBuilder.Entity("PowerUp.Models.ModuloEducativoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<int>("Nivel")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Subtitulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("ThumbLinkId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.HasKey("Id");

                    b.HasIndex("ThumbLinkId");

                    b.ToTable("modulo_educativo");
                });

            modelBuilder.Entity("PowerUp.Models.PerguntaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("QuizId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("pergunta");
                });

            modelBuilder.Entity("PowerUp.Models.PermissaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("permissao");
                });

            modelBuilder.Entity("PowerUp.Models.QuizModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<int>("ModuloEducativoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("NotaMinima")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("nota_minima");

                    b.HasKey("Id");

                    b.HasIndex("ModuloEducativoId");

                    b.ToTable("quiz");
                });

            modelBuilder.Entity("PowerUp.Models.RankingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.HasKey("Id");

                    b.ToTable("ranking");
                });

            modelBuilder.Entity("PowerUp.Models.RecompensaConfigModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustoPontos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("custo_pontos");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int>("RecompensaTipoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("RecompensaTipoId");

                    b.ToTable("recompensa_config");
                });

            modelBuilder.Entity("PowerUp.Models.RecompensaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PontosUtilizados")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("pontos_utilizados");

                    b.Property<int>("RecompensaConfigId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("RecompensaConfigId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("recompensa");
                });

            modelBuilder.Entity("PowerUp.Models.RecompensaTipoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.HasKey("Id");

                    b.ToTable("recompensa_tipo");
                });

            modelBuilder.Entity("PowerUp.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("firebase_uid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int?>("RankingId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("RankingId");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("PowerUp.Models.UsuarioPermissaoModel", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Permissao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Usuario")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("UsuarioId", "PermissaoId");

                    b.ToTable("usuario_permissao");
                });

            modelBuilder.Entity("PowerUp.Models.AlternativaModel", b =>
                {
                    b.HasOne("PowerUp.Models.PerguntaModel", "Pergunta")
                        .WithMany()
                        .HasForeignKey("PerguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pergunta");
                });

            modelBuilder.Entity("PowerUp.Models.ArtigoModel", b =>
                {
                    b.HasOne("PowerUp.Models.ModuloEducativoModel", "ModuloEducativo")
                        .WithMany()
                        .HasForeignKey("ModuloEducativoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerUp.Models.LinkModel", "ThumbLink")
                        .WithMany()
                        .HasForeignKey("ThumbLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuloEducativo");

                    b.Navigation("ThumbLink");
                });

            modelBuilder.Entity("PowerUp.Models.DesafioModel", b =>
                {
                    b.HasOne("PowerUp.Models.QuizModel", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerUp.Models.LinkModel", "ThumbLink")
                        .WithMany()
                        .HasForeignKey("ThumbLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("ThumbLink");
                });

            modelBuilder.Entity("PowerUp.Models.EmblemaConfigModel", b =>
                {
                    b.HasOne("PowerUp.Models.EmblemaTipoModel", "EmblemaTipo")
                        .WithMany()
                        .HasForeignKey("EmblemaTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerUp.Models.QuizModel", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmblemaTipo");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("PowerUp.Models.EmblemaModel", b =>
                {
                    b.HasOne("PowerUp.Models.EmblemaConfigModel", "EmblemaConfig")
                        .WithMany()
                        .HasForeignKey("EmblemaConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerUp.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmblemaConfig");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PowerUp.Models.EmblemaTipoModel", b =>
                {
                    b.HasOne("PowerUp.Models.LinkModel", "ImageLink")
                        .WithMany()
                        .HasForeignKey("ImageLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageLink");
                });

            modelBuilder.Entity("PowerUp.Models.MissaoModel", b =>
                {
                    b.HasOne("PowerUp.Models.MissaoConfigModel", "MissaoConfig")
                        .WithMany()
                        .HasForeignKey("MissaoConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerUp.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MissaoConfig");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PowerUp.Models.ModuloEducativoModel", b =>
                {
                    b.HasOne("PowerUp.Models.LinkModel", "ThumbLink")
                        .WithMany()
                        .HasForeignKey("ThumbLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThumbLink");
                });

            modelBuilder.Entity("PowerUp.Models.PerguntaModel", b =>
                {
                    b.HasOne("PowerUp.Models.QuizModel", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("PowerUp.Models.QuizModel", b =>
                {
                    b.HasOne("PowerUp.Models.ModuloEducativoModel", "ModuloEducativo")
                        .WithMany()
                        .HasForeignKey("ModuloEducativoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuloEducativo");
                });

            modelBuilder.Entity("PowerUp.Models.RecompensaConfigModel", b =>
                {
                    b.HasOne("PowerUp.Models.RecompensaTipoModel", "RecompensaTipo")
                        .WithMany()
                        .HasForeignKey("RecompensaTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecompensaTipo");
                });

            modelBuilder.Entity("PowerUp.Models.RecompensaModel", b =>
                {
                    b.HasOne("PowerUp.Models.RecompensaConfigModel", "RecompensaConfig")
                        .WithMany()
                        .HasForeignKey("RecompensaConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PowerUp.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecompensaConfig");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PowerUp.Models.UsuarioModel", b =>
                {
                    b.HasOne("PowerUp.Models.RankingModel", "Ranking")
                        .WithMany()
                        .HasForeignKey("RankingId");

                    b.Navigation("Ranking");
                });
#pragma warning restore 612, 618
        }
    }
}
